version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-web-app
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
