
version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 23
        commands:
            - npm install
    
    build:
        commands:
            - npm run build

artifacts:
    files:
        - dist/**/*
        - appspec.yml
        - scripts/**/*
